spring.application.name=juno
spring.jpa.hibernate.ddl-auto=validate
spring.security.user.name=dev
spring.security.user.password=dev
spring.mail.host=localhost
spring.mail.port=1025
juno.mail.from=Juno <no-reply@juno.local>
